services:
  - type: web
    name: shortliens
    env: node
    buildCommand: npm install
    startCommand: npm start
    plan: free
    autoDeploy: true
    nodeVersion: 18
    envVars:
      - key: NODE_ENV
        value: production
